<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>canbus_bridge</name>
  <version>0.0.1</version>
  <description>ROS2 bridge for Industrial CANbus UDP Multicast data</description>
  <maintainer email="enesuslu15@gmail.com">Enes Uslu</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>canbus_msgs</depend>
  
  <exec_depend>python3-can</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
